### ISSUE TITLE
Another build failure on x86_64 Fedora 37 (objcopy failing?)

### ISSUE THREAD

**Issue by felixphew** [leifliddy/asahi-fedora-usb#4]
Hi! After installing the listed dependencies on my (x86_64) Fedora 37 box, I encountered an error when running the latest (as of this morning) install script.

<details><summary>log</summary>

```
### Preparing USB device...
GPT fdisk (gdisk) version 1.0.9

Partition table scan:
  MBR: protective
  BSD: not present
  APM: not present
  GPT: present

Found valid GPT with protective MBR; using GPT.

Command (? for help): This option deletes all partitions and creates a new protective MBR.
Proceed? (Y/N): 
Command (? for help): Partition number (1-128, default 1): First sector (34-30285790, default = 2048) or {+-}size{KMGTP}: Last sector (2048-30285790, default = 30283775) or {+-}size{KMGTP}: Current type is 8300 (Linux filesystem)
Hex code or GUID (L to show codes, Enter = 8300): Changed type of partition to 'EFI system partition'

Command (? for help): Partition number (2-128, default 2): First sector (34-30285790, default = 4196352) or {+-}size{KMGTP}: Last sector (4196352-30285790, default = 30283775) or {+-}size{KMGTP}: Current type is 8300 (Linux filesystem)
Hex code or GUID (L to show codes, Enter = 8300): Changed type of partition to 'Linux filesystem'

Command (? for help): 
Final checks complete. About to write GPT data. THIS WILL OVERWRITE EXISTING
PARTITIONS!!

Do you want to proceed? (Y/N): OK; writing new GUID partition table (GPT) to /dev/sdb.
The operation has completed successfully.
mkfs.fat 4.2 (2021-01-31)
mke2fs 1.46.5 (30-Dec-2021)
Creating filesystem with 3260928 4k blocks and 816000 inodes
Filesystem UUID: d747cb2a-aff1-4e47-8a33-c4d9b7475df9
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (16384 blocks): done
Writing superblocks and filesystem accounting information: done   

‣ Removing output files…
--2023-01-18 11:36:33--  https://leifliddy.com/asahi-linux/asahi-linux.repo
Resolving leifliddy.com (leifliddy.com)... 46.101.247.100
Connecting to leifliddy.com (leifliddy.com)|46.101.247.100|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 536 [text/plain]
Saving to: ‘mkosi.skeleton/etc/yum.repos.d/asahi-linux.repo’

mkosi.skeleton/etc/yum.repos.d/asahi-linux.repo                     100%[===================================================================================================================================================================>]     536  --.-KB/s    in 0s      

2023-01-18 11:36:34 (2.78 MB/s) - ‘mkosi.skeleton/etc/yum.repos.d/asahi-linux.repo’ saved [536/536]

‣ Removing output files…
‣ Detaching namespace
‣ Setting up temporary workspace.
‣ Temporary workspace set up in /var/tmp/mkosi-tk3znktv
‣ Running second (final) stage…
‣  Creating image with partition table…
Disk /home/felix/Documents/Projects/fedora-asahi/asahi-fedora-usb/.mkosi-wggusxhe: 1.45 GiB, 1556967424 bytes, 3040952 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

>>> Script header accepted.
>>> Script header accepted.
>>> Script header accepted.
>>> Created a new GPT disklabel (GUID: 4ACF3ED1-81AA-1F44-918D-8300557DC50C).
/home/felix/Documents/Projects/fedora-asahi/asahi-fedora-usb/.mkosi-wggusxhe1: Created a new partition 1 of type 'EFI System' and of size 256 MiB.
/home/felix/Documents/Projects/fedora-asahi/asahi-fedora-usb/.mkosi-wggusxhe2: Created a new partition 2 of type 'Linux root (ARM-64)' and of size 1.2 GiB.
/home/felix/Documents/Projects/fedora-asahi/asahi-fedora-usb/.mkosi-wggusxhe3: Done.

New situation:
Disklabel type: gpt
Disk identifier: 4ACF3ED1-81AA-1F44-918D-8300557DC50C

Device                                                                         Start     End Sectors  Size Type
/home/felix/Documents/Projects/fedora-asahi/asahi-fedora-usb/.mkosi-wggusxhe1     40  524327  524288  256M EFI System
/home/felix/Documents/Projects/fedora-asahi/asahi-fedora-usb/.mkosi-wggusxhe2 524328 3040911 2516584  1.2G Linux root (ARM-64)

The partition table has been altered.
‣  Created image with partition table as /home/felix/Documents/Projects/fedora-asahi/asahi-fedora-usb/.mkosi-wggusxhe
‣  Attaching /home/felix/Documents/Projects/fedora-asahi/asahi-fedora-usb/.mkosi-wggusxhe as loopback…
‣   Formatting ESP partition
mkfs.fat 4.2 (2021-01-31)
‣   Formatting root partition…
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks: done                            
Creating filesystem with 314573 4k blocks and 78720 inodes
Filesystem UUID: 8f41c475-cb1f-4169-b67c-b31887c2780d
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (8192 blocks): done
Writing superblocks and filesystem accounting information: done 

‣   Mounting image…
‣    Setting up basic OS tree…
‣    Copying in skeleton file trees…
‣    Mounting Package Cache
‣     Installing Fedora Linux…
‣      Mounting API VFS…

...dnf install log with no errors trimmed...

Installed:
  NetworkManager-1:1.40.6-1.fc37.aarch64             NetworkManager-libnm-1:1.40.6-1.fc37.aarch64         NetworkManager-wifi-1:1.40.6-1.fc37.aarch64          alsa-lib-1.2.8-2.fc37.aarch64                          alsa-ucm-1.2.8-2.fc37.noarch                           
  alsa-ucm-asahi-1-5.fc37.noarch                     alternatives-1.21-1.fc37.aarch64                     arch-install-scripts-27-1.fc37.noarch                archlinux-keyring-20221220-1.fc37.noarch               asahi-scripts-20221206-1.fc37.noarch                   
  audit-3.0.9-1.fc37.aarch64                         audit-libs-3.0.9-1.fc37.aarch64                      authselect-1.4.2-1.fc37.aarch64                      authselect-libs-1.4.2-1.fc37.aarch64                   basesystem-11-14.fc37.noarch                           
  bash-5.2.15-1.fc37.aarch64                         bash-completion-1:2.11-8.fc37.noarch                 binutils-2.38-25.fc37.aarch64                        binutils-gold-2.38-25.fc37.aarch64                     bsdtar-3.6.1-3.fc37.aarch64                            
  btrfs-progs-6.1.2-1.fc37.aarch64                   bzip2-libs-1.0.8-12.fc37.aarch64                     ca-certificates-2022.2.54-5.fc37.noarch              cloud-utils-growpart-0.31-11.fc37.noarch               coreutils-9.1-7.fc37.aarch64                           
  coreutils-common-9.1-7.fc37.aarch64                cpio-2.13-13.fc37.aarch64                            cracklib-2.9.7-30.fc37.aarch64                       crypto-policies-20220815-1.gite4ed860.fc37.noarch      cryptsetup-libs-2.5.0-1.fc37.aarch64                   
  curl-7.85.0-5.fc37.aarch64                         cyrus-sasl-lib-2.1.28-8.fc37.aarch64                 dbus-1:1.14.4-1.fc37.aarch64                         dbus-broker-32-1.fc37.aarch64                          dbus-common-1:1.14.4-1.fc37.noarch                     
  dbus-libs-1:1.14.4-1.fc37.aarch64                  device-mapper-1.02.175-9.fc37.aarch64                device-mapper-libs-1.02.175-9.fc37.aarch64           dhcp-client-12:4.4.3-4.P1.fc37.aarch64                 dhcp-common-12:4.4.3-4.P1.fc37.noarch                  
  diffutils-3.8-3.fc37.aarch64                       dnf-4.14.0-1.fc37.noarch                             dnf-data-4.14.0-1.fc37.noarch                        dnf-plugins-core-4.3.1-1.fc37.noarch                   dosfstools-4.2-4.fc37.aarch64                          
  dracut-057-5.fc37.aarch64                          dracut-asahi-20221206-1.fc37.noarch                  e2fsprogs-1.46.5-3.fc37.aarch64                      e2fsprogs-libs-1.46.5-3.fc37.aarch64                   efivar-38-5.fc37.aarch64                               
  efivar-libs-38-5.fc37.aarch64                      elfutils-debuginfod-client-0.188-3.fc37.aarch64      elfutils-default-yama-scope-0.188-3.fc37.noarch      elfutils-libelf-0.188-3.fc37.aarch64                   elfutils-libs-0.188-3.fc37.aarch64                     
  expat-2.5.0-1.fc37.aarch64                         fedora-gpg-keys-37-1.noarch                          fedora-release-37-15.noarch                          fedora-release-common-37-15.noarch                     fedora-release-identity-basic-37-15.noarch             
  fedora-repos-37-1.noarch                           file-libs-5.42-4.fc37.aarch64                        filesystem-3.18-2.fc37.aarch64                       findutils-1:4.9.0-2.fc37.aarch64                       fuse-libs-2.9.9-15.fc37.aarch64                        
  gawk-5.1.1-4.fc37.aarch64                          gdbm-libs-1:1.23-2.fc37.aarch64                      glib2-2.74.1-2.fc37.aarch64                          glibc-2.36-9.fc37.aarch64                              glibc-common-2.36-9.fc37.aarch64                       
  glibc-minimal-langpack-2.36-9.fc37.aarch64         gmp-1:6.2.1-3.fc37.aarch64                           gnupg2-2.3.8-1.fc37.aarch64                          gnutls-3.7.8-3.fc37.aarch64                            gpgme-1.17.0-4.fc37.aarch64                            
  gpm-libs-1.20.7-41.fc37.aarch64                    grep-3.7-4.fc37.aarch64                              groff-base-1.22.4-10.fc37.aarch64                    gzip-1.12-2.fc37.aarch64                               hostname-3.23-7.fc37.aarch64                           
  hwdata-0.366-1.fc37.noarch                         ima-evm-utils-1.4-6.fc37.aarch64                     inih-56-2.fc37.aarch64                               initscripts-service-10.17-1.fc37.noarch                ipcalc-1.0.2-1.fc37.aarch64                            
  iproute-5.18.0-2.fc37.aarch64                      iputils-20221126-1.fc37.aarch64                      iw-5.9-5.fc37.aarch64                                json-c-0.16-3.fc37.aarch64                             kbd-2.5.1-3.fc37.aarch64                               
  kbd-legacy-2.5.1-3.fc37.noarch                     kbd-misc-2.5.1-3.fc37.noarch                         kernel-6.2.0-0.rc3.asahi5.1.fc37.aarch64             kernel-core-6.2.0-0.rc3.asahi5.1.fc37.aarch64          kernel-modules-6.2.0-0.rc3.asahi5.1.fc37.aarch64       
  keyrings-filesystem-1-17.fc37.noarch               keyutils-libs-1.6.1-5.fc37.aarch64                   kmod-30-2.fc37.aarch64                               kmod-libs-30-2.fc37.aarch64                            krb5-libs-1.19.2-13.fc37.aarch64                       
  less-590-5.fc37.aarch64                            libacl-2.3.1-4.fc37.aarch64                          libalpm-6.0.1-5.fc37.aarch64                         libarchive-3.6.1-3.fc37.aarch64                        libargon2-20190702-1.fc37.aarch64                      
  libassuan-2.5.5-5.fc37.aarch64                     libattr-2.5.1-5.fc37.aarch64                         libb2-0.98.1-7.fc37.aarch64                          libblkid-2.38.1-1.fc37.aarch64                         libbpf-2:0.8.0-2.fc37.aarch64                          
  libbrotli-1.0.9-9.fc37.aarch64                     libcap-2.48-5.fc37.aarch64                           libcap-ng-0.8.3-3.fc37.aarch64                       libcbor-0.7.0-7.fc37.aarch64                           libcom_err-1.46.5-3.fc37.aarch64                       
  libcomps-0.1.18-4.fc37.aarch64                     libcurl-7.85.0-5.fc37.aarch64                        libdb-5.3.28-53.fc37.aarch64                         libdnf-0.68.0-1.fc37.aarch64                           libeconf-0.4.0-4.fc37.aarch64                          
  libedit-3.1-43.20221009cvs.fc37.aarch64            libevent-2.1.12-7.fc37.aarch64                       libfdisk-2.38.1-1.fc37.aarch64                       libffi-3.4.2-9.fc37.aarch64                            libfido2-1.11.0-3.fc37.aarch64                         
  libfsverity-1.4-8.fc37.aarch64                     libgcc-12.2.1-4.fc37.aarch64                         libgcrypt-1.10.1-4.fc37.aarch64                      libgomp-12.2.1-4.fc37.aarch64                          libgpg-error-1.46-1.fc37.aarch64                       
  libidn2-2.3.4-1.fc37.aarch64                       libkcapi-1.4.0-2.fc37.aarch64                        libkcapi-hmaccalc-1.4.0-2.fc37.aarch64               libksba-1.6.3-1.fc37.aarch64                           libmetalink-0.1.3-28.fc37.aarch64                      
  libmnl-1.0.5-1.fc37.aarch64                        libmodulemd-2.14.0-4.fc37.aarch64                    libmount-2.38.1-1.fc37.aarch64                       libndp-1.8-4.fc37.aarch64                              libnghttp2-1.51.0-1.fc37.aarch64                       
  libnl3-3.7.0-2.fc37.aarch64                        libnsl2-2.0.0-4.fc37.aarch64                         libpipeline-1.5.6-2.fc37.aarch64                     libpkgconf-1.8.0-3.fc37.aarch64                        libpsl-0.21.1-6.fc37.aarch64                           
  libpwquality-1.4.5-1.fc37.aarch64                  librepo-1.15.1-1.fc37.aarch64                        libreport-filesystem-2.17.4-1.fc37.noarch            libseccomp-2.5.3-3.fc37.aarch64                        libselinux-3.4-5.fc37.aarch64                          
  libselinux-utils-3.4-5.fc37.aarch64                libsemanage-3.4-5.fc37.aarch64                       libsepol-3.4-3.fc37.aarch64                          libsigsegv-2.14-3.fc37.aarch64                         libsmartcols-2.38.1-1.fc37.aarch64                     
  libsodium-1.0.18-10.fc37.aarch64                   libsolv-0.7.22-3.fc37.aarch64                        libss-1.46.5-3.fc37.aarch64                          libssh-0.10.4-2.fc37.aarch64                           libssh-config-0.10.4-2.fc37.noarch                     
  libstdc++-12.2.1-4.fc37.aarch64                    libtasn1-4.19.0-1.fc37.aarch64                       libtirpc-1.3.3-0.fc37.aarch64                        libunistring-1.0-2.fc37.aarch64                        libusb1-1.0.25-9.fc37.aarch64                          
  libuser-0.63-13.fc37.aarch64                       libutempter-1.2.1-7.fc37.aarch64                     libuuid-2.38.1-1.fc37.aarch64                        libverto-0.3.2-4.fc37.aarch64                          libxcrypt-4.4.33-4.fc37.aarch64                        
  libxml2-2.10.3-2.fc37.aarch64                      libyaml-0.2.5-8.fc37.aarch64                         libzstd-1.5.2-3.fc37.aarch64                         light-1.2.2-7.fc37.aarch64                             linux-firmware-20221214-145.fc37.noarch                
  linux-firmware-vendor-20221206-1.fc37.noarch       linux-firmware-whence-20221214-145.fc37.noarch       lua-libs-5.4.4-7.fc37.aarch64                        lz4-libs-1.9.4-1.fc37.aarch64                          lzo-2.10-7.fc37.aarch64                                
  man-db-2.10.2-2.fc37.aarch64                       man-pages-5.13-4.fc37.noarch                         mpdecimal-2.5.1-4.fc37.aarch64                       mpfr-4.1.0-10.fc37.aarch64                             ncurses-6.3-4.20220501.fc37.aarch64                    
  ncurses-base-6.3-4.20220501.fc37.noarch            ncurses-libs-6.3-4.20220501.fc37.aarch64             net-tools-2.0-0.64.20160912git.fc37.aarch64          nettle-3.8-2.fc37.aarch64                              npth-1.6-9.fc37.aarch64                                
  openldap-2.6.3-1.fc37.aarch64                      openssh-8.8p1-7.fc37.aarch64                         openssh-clients-8.8p1-7.fc37.aarch64                 openssh-server-8.8p1-7.fc37.aarch64                    openssl-libs-1:3.0.5-3.fc37.aarch64                    
  p11-kit-0.24.1-3.fc37.aarch64                      p11-kit-trust-0.24.1-3.fc37.aarch64                  pacman-6.0.1-5.fc37.aarch64                          pacman-filesystem-6.0.1-5.fc37.noarch                  pam-1.5.2-14.fc37.aarch64                              
  pam-libs-1.5.2-14.fc37.aarch64                     passwd-0.80-13.fc37.aarch64                          pciutils-3.9.0-2.fc37.aarch64                        pciutils-libs-3.9.0-2.fc37.aarch64                     pcre-8.45-1.fc37.2.aarch64                             
  pcre2-10.40-1.fc37.1.aarch64                       pcre2-syntax-10.40-1.fc37.1.noarch                   perl-B-1.83-492.fc37.aarch64                         perl-Carp-1.52-489.fc37.noarch                         perl-Class-Struct-0.66-492.fc37.noarch                 
  perl-Data-Dumper-2.184-490.fc37.aarch64            perl-DynaLoader-1.52-492.fc37.aarch64                perl-Encode-4:3.19-492.fc37.aarch64                  perl-Errno-1.36-492.fc37.aarch64                       perl-Exporter-5.77-489.fc37.noarch                     
  perl-Fcntl-1.15-492.fc37.aarch64                   perl-File-Basename-2.85-492.fc37.noarch              perl-File-Find-1.40-492.fc37.noarch                  perl-File-Path-2.18-489.fc37.noarch                    perl-File-Temp-1:0.231.100-489.fc37.noarch             
  perl-File-stat-1.12-492.fc37.noarch                perl-FileHandle-2.03-492.fc37.noarch                 perl-Getopt-Long-1:2.54-1.fc37.noarch                perl-Getopt-Std-1.13-492.fc37.noarch                   perl-HTTP-Tiny-0.082-1.fc37.noarch                     
  perl-I18N-LangTags-0.45-492.fc37.noarch            perl-IO-1.50-492.fc37.aarch64                        perl-IPC-Open3-1.22-492.fc37.noarch                  perl-Locale-Maketext-1.32-1.fc37.noarch                perl-Locale-Maketext-Simple-1:0.21-492.fc37.noarch     
  perl-MIME-Base64-3.16-489.fc37.aarch64             perl-Module-CoreList-1:5.20221220-1.fc37.noarch      perl-Module-Load-1:0.36-489.fc37.noarch              perl-Module-Load-Conditional-0.74-489.fc37.noarch      perl-Module-Metadata-1.000037-489.fc37.noarch          
  perl-POSIX-2.03-492.fc37.aarch64                   perl-Params-Check-1:0.38-489.fc37.noarch             perl-PathTools-3.84-489.fc37.aarch64                 perl-Pod-Escapes-1:1.07-489.fc37.noarch                perl-Pod-Perldoc-3.28.01-490.fc37.noarch               
  perl-Pod-Simple-1:3.43-490.fc37.noarch             perl-Pod-Usage-4:2.03-3.fc37.noarch                  perl-Scalar-List-Utils-5:1.63-489.fc37.aarch64       perl-SelectSaver-1.02-492.fc37.noarch                  perl-Socket-4:2.036-1.fc37.aarch64                     
  perl-Storable-1:3.26-489.fc37.aarch64              perl-Symbol-1.09-492.fc37.noarch                     perl-Term-ANSIColor-5.01-490.fc37.noarch             perl-Term-Cap-1.17-489.fc37.noarch                     perl-Text-ParseWords-3.31-489.fc37.noarch              
  perl-Text-Tabs+Wrap-2021.0814-489.fc37.noarch      perl-Time-Local-2:1.300-489.fc37.noarch              perl-base-2.27-492.fc37.noarch                       perl-constant-1.33-490.fc37.noarch                     perl-if-0.61.000-492.fc37.noarch                       
  perl-interpreter-4:5.36.0-492.fc37.aarch64         perl-libs-4:5.36.0-492.fc37.aarch64                  perl-locale-1.10-492.fc37.noarch                     perl-mro-1.26-492.fc37.aarch64                         perl-overload-1.35-492.fc37.noarch                     
  perl-overloading-0.02-492.fc37.noarch              perl-parent-1:0.238-489.fc37.noarch                  perl-podlators-1:4.14-489.fc37.noarch                perl-subs-1.04-492.fc37.noarch                         perl-vars-1.05-492.fc37.noarch                         
  perl-version-8:0.99.29-490.fc37.aarch64            pkgconf-1.8.0-3.fc37.aarch64                         pkgconf-m4-1.8.0-3.fc37.noarch                       pkgconf-pkg-config-1.8.0-3.fc37.aarch64                policycoreutils-3.4-6.fc37.aarch64                     
  popt-1.19-1.fc37.aarch64                           procps-ng-3.3.17-6.fc37.2.aarch64                    psmisc-23.4-4.fc37.aarch64                           publicsuffix-list-dafsa-20210518-5.fc37.noarch         python-pip-wheel-22.2.2-3.fc37.noarch                  
  python-setuptools-wheel-62.6.0-2.fc37.noarch       python3-3.11.1-1.fc37.aarch64                        python3-dateutil-1:2.8.2-4.fc37.noarch               python3-dbus-1.3.2-1.fc37.aarch64                      python3-distro-1.7.0-3.fc37.noarch                     
  python3-dnf-4.14.0-1.fc37.noarch                   python3-dnf-plugins-core-4.3.1-1.fc37.noarch         python3-gpg-1.17.0-4.fc37.aarch64                    python3-hawkey-0.68.0-1.fc37.aarch64                   python3-libcomps-0.1.18-4.fc37.aarch64                 
  python3-libdnf-0.68.0-1.fc37.aarch64               python3-libs-3.11.1-1.fc37.aarch64                   python3-rpm-4.18.0-1.fc37.aarch64                    python3-six-1.16.0-8.fc37.noarch                       readline-8.2-2.fc37.aarch64                            
  rootfiles-8.1-32.fc37.noarch                       rpm-4.18.0-1.fc37.aarch64                            rpm-build-libs-4.18.0-1.fc37.aarch64                 rpm-libs-4.18.0-1.fc37.aarch64                         rpm-plugin-selinux-4.18.0-1.fc37.aarch64               
  rpm-sign-libs-4.18.0-1.fc37.aarch64                rsync-3.2.7-1.fc37.aarch64                           sed-4.8-11.fc37.aarch64                              selinux-policy-37.17-1.fc37.noarch                     selinux-policy-targeted-37.17-1.fc37.noarch            
  setup-2.14.1-2.fc37.noarch                         shadow-utils-2:4.12.3-4.fc37.aarch64                 sqlite-libs-3.40.0-1.fc37.aarch64                    sudo-1.9.11-4.p3.fc37.aarch64                          systemd-251.10-588.fc37.aarch64                        
  systemd-libs-251.10-588.fc37.aarch64               systemd-pam-251.10-588.fc37.aarch64                  systemd-udev-251.10-588.fc37.aarch64                 tar-2:1.34-5.fc37.aarch64                              tpm2-tss-3.2.1-1.fc37.aarch64                          
  tzdata-2022g-1.fc37.noarch                         usbutils-014-3.fc37.aarch64                          userspace-rcu-0.13.0-5.fc37.aarch64                  util-linux-2.38.1-1.fc37.aarch64                       util-linux-core-2.38.1-1.fc37.aarch64                  
  vim-common-2:9.0.1182-1.fc37.aarch64               vim-data-2:9.0.1182-1.fc37.noarch                    vim-enhanced-2:9.0.1182-1.fc37.aarch64               vim-filesystem-2:9.0.1182-1.fc37.noarch                vim-minimal-2:9.0.1182-1.fc37.aarch64                  
  wget-1.21.3-4.fc37.aarch64                         which-2.21-35.fc37.aarch64                           wireless-regdb-2022.06.06-2.fc37.noarch              wpa_supplicant-1:2.10-5.fc37.aarch64                   xfsprogs-5.18.0-3.fc37.aarch64                         
  xxhash-libs-0.8.1-3.fc37.aarch64                   xz-5.2.5-10.fc37.aarch64                             xz-libs-5.2.5-10.fc37.aarch64                        zchunk-libs-1.2.3-1.fc37.aarch64                       zlib-1.2.12-5.fc37.aarch64                             
  zram-generator-1.1.2-2.fc37.aarch64                zram-generator-defaults-1.1.2-2.fc37.noarch         

Complete!
‣      Unmounting API VFS…
‣    Unmounting Package Cache
‣    Assigning hostname
‣    Setting root password
‣    Generating initramfs images…
/usr/bin/dracut: line 1054: /sys/module/firmware_class/parameters/path: No such file or directory
‣    Installing boot loader…
Copied "/usr/lib/systemd/boot/efi/systemd-bootaa64.efi" to "/efi/EFI/systemd/systemd-bootaa64.efi".
Copied "/usr/lib/systemd/boot/efi/systemd-bootaa64.efi" to "/efi/EFI/BOOT/BOOTAA64.EFI".
Random seed file /efi/loader/random-seed successfully written (32 bytes).
‣    Recording packages in manifest…
‣    Resetting machine ID
‣    Removing random seed
‣    Trimming File System
/var/tmp/mkosi-tk3znktv/root: 496.9 MiB (521023488 bytes) trimmed
‣   Unmounting image…
‣   Mounting image…
‣    Generating combined kernel + initrd boot file…
objcopy: /var/tmp/mkosi-tk3znktv/root/lib/systemd/boot/efi/linuxaa64.efi.stub: file format not recognized
objcopy: --change-section-vma .initrd=0x0000000003000000 never used
objcopy: --change-section-vma .linux=0x0000000002000000 never used
objcopy: --change-section-vma .cmdline=0x0000000000030000 never used
objcopy: --change-section-vma .osrel=0x0000000000020000 never used
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.11/site-packages/mkosi/__main__.py", line 45, in <module>
    main()
  File "/usr/lib64/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mkosi/__main__.py", line 41, in main
    run_verb(a)
  File "/usr/lib/python3.11/site-packages/mkosi/__init__.py", line 8254, in run_verb
    manifest = build_stuff(config)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mkosi/__init__.py", line 7559, in build_stuff
    image = build_image(state, manifest=manifest)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mkosi/__init__.py", line 7342, in build_image
    install_unified_kernel(state, root_hash, mount)
  File "/usr/lib/python3.11/site-packages/mkosi/__init__.py", line 4080, in install_unified_kernel
    run(cmd)
  File "/usr/lib/python3.11/site-packages/mkosi/backend.py", line 860, in run
    return subprocess.run(cmdline, check=check, stdout=stdout, stderr=stderr, env={**os.environ, **env}, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 569, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['objcopy', '--add-section', '.osrel=/var/tmp/mkosi-tk3znktv/root/usr/lib/os-release', '--change-section-vma', '.osrel=0x20000', '--add-section', '.cmdline=/var/tmp/mkosi-tk3znktv/cmdline', '--change-section-vma', '.cmdline=0x30000', '--add-section', '.linux=/var/tmp/mkosi-tk3znktv/root/lib/modules/6.2.0-0.rc3.asahi5.1.fc37.aarch64/vmlinuz', '--change-section-vma', '.linux=0x2000000', '--add-section', '.initrd=/var/tmp/mkosi-tk3znktv/root/efi/46d1386bbc7c40baacedc67d2cbab734/6.2.0-0.rc3.asahi5.1.fc37.aarch64/initrd', '--change-section-vma', '.initrd=0x3000000', '/var/tmp/mkosi-tk3znktv/root/lib/systemd/boot/efi/linuxaa64.efi.stub', '/var/tmp/mkosi-tk3znktv/root/efi/EFI/Linux/fedora-6.2.0-0.rc3.asahi5.1.fc37.aarch64.efi']' returned non-zero exit status 1.
```

</details>

```objcopy: /var/tmp/mkosi-tk3znktv/root/lib/systemd/boot/efi/linuxaa64.efi.stub: file format not recognized``` appears to be the problem.

I can't say I'm 100% familiar with how this process works, but - maybe it's somehow calling the wrong (i.e. the host's) objcopy? Or maybe the file in question doesn't exist? (idk, the script cleans up after itself so I couldn't check)

Any advice would be appreciated. Happy to try things out to troubleshoot, of course.

**Comment by leifliddy** [comment]
It seems like `mkosi` is a bit of a moving target, as they're constantly pushing out major changes.  
So crossarch building use to work -- there's an active issue for that here: https://github.com/systemd/mkosi/issues/1155
For now, this needs to be built on an `aarch64` system.

**Comment by leifliddy** [comment]
I have a solution one sec....

**Comment by felixphew** [comment]
I wonder how much extra work it'd be to cut `mkosi` out of the loop entirely and simply use `dnf --installroot` directly? (Not as a quick fix, of course, rather as a path to move forward if `mkosi` is unstable.)

**Comment by leifliddy** [comment]
>dnf --installroot directly

That's not a bad idea. I'm not really using much of `mkosi` at this point. 

You can crossbuild this branch -- which uses grub
https://github.com/leifliddy/asahi-fedora-usb/tree/v1

It's a bit slow to jump from uboot --> grub as it uses the `shim-aa64` provided `/BOOTAA64.EFI` bootloader
I need to clean up a few things up, nothing major. I'll have time tonight to do that. 

Oh, you do need to install `mkosi` from main to build this
`python3 -m pip install --user git+https://github.com/systemd/mkosi.git`

Anyways, let me know if that works for you.

**Comment by felixphew** [comment]
After a silly mistake on my part (forgetting PATH doesn't always get passed through `sudo`), yes, it works :)
